### ISSUE TITLE
Latest update date clarification

### ISSUE THREAD

**Issue by ErenMustafaGit** [FranckG28/Vine#27]
~~Updated 48 min ago but navbar shows that the last update took place "4 day ago"~~

need to be more explicit (tooltip + modify the sentence "Dernière mise à jour")

![image](https://github.com/FranckG28/Vine/assets/82711747/3a2c92c5-09e8-4ab7-abba-eb84bb563a8d)

**Comment by FranckG28** [comment]
It's correct, It displays the last complete update date ;)
I should improve this to make that clear

**Comment by ErenMustafaGit** [comment]
Is it not better to display the last update (complete or not ?)
What is the purpose to display the last complete update ?

**Comment by FranckG28** [comment]
There is 2 type of updates :

- partial : it take the product visible on the current page & send it to the API. This is great to have ultra frequent update. However, it doesn't allow us to know the availability of product, because if it has disappeared on the current page he has maybe just moved to the next page. That why we need full updates.

- full : the script goes through all the pages to build a complete list of product. Then, we can compute the diff to see what has disappeared.

But you are right, no one can understand this since it's not written anywhere. I still think that this last FULL update date is useful, but his meaning need to be explicit to the user.

I will add an info tooltip to the last update badge ;)

**Comment by ErenMustafaGit** [comment]
New products from frequent partial update will be easily known by the user with #11 ✅ 
And YES the full update badge need to be more explicit (tooltip + modify the sentence "Dernière mise à jour")

Modifying this issue from bug to feature (Improve UX of the update badge)

**Comment by ErenMustafaGit** [comment]
The UI of this badge is too similar to Highlight component for new products : confusing because it's 2 different definition of "updated"
![image](https://github.com/FranckG28/Vine/assets/82711747/abf6f8d6-1696-4dd2-846a-e8e4d0ae6387)

**Comment by FranckG28** [comment]
> The UI of this badge is too similar to Highlight component for new products : confusing because it's 2 different definition of "updated" ![image](https://user-images.githubusercontent.com/82711747/266795927-abf6f8d6-1696-4dd2-846a-e8e4d0ae6387.png)

In the past this badge was for newly added products. It's removed now and i think it is more appropriate for an unread badge. This will be his only usage. Do you think it is still confusing for the user ?

**Comment by ErenMustafaGit** [comment]
> > The UI of this badge is too similar to Highlight component for new products : confusing because it's 2 different definition of "updated" ![image](https://user-images.githubusercontent.com/82711747/266795927-abf6f8d6-1696-4dd2-846a-e8e4d0ae6387.png)
> 
> In the past this badge was for newly added products. It's removed now and i think it is more appropriate for an unread badge. This will be his only usage. Do you think it is still confusing for the user ?

Yes, this unread badge may be still confusing for some users, because the notion of "unreaded products" and "fully updated products" may be similar for common users. Using the same color and badge is a bit tricky

**Comment by FranckG28** [comment]
Hmm. Maybe in another color like green it will be better ?
I don't have a better idea for an unread indicator

**Comment by FranckG28** [comment]
![Image](https://github.com/FranckG28/Vine/assets/19238963/fa415aa1-abc7-4fa8-aec8-7e048d77292f)

What do you think ?
